name: Triggering on Paths

on:
  push:
    branches:
      - main
    paths:
      - 'house/room/bed/hi.js'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
#######################################################

      - name: Run if file exists.
        run: |
          file_exists=$(test -e ./house/room/bed/hi.js && echo true-x0x0 || echo false)
          echo $file_exists
          
