name: Triggering on Paths

on:
  push:
    branches:
      - main
    paths:
      - 'house/room/bed/hi.js'

jobs:
  job1_check_file_exist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
    
    
  job2_run_commands:
    runs-on: ubuntu-latest
    needs: [job1_check_file_exist]
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install prerequisites
        run: |
          sudo apt install python3-pip
          pip3 install terrasnek
          whoami
          pwd
          tree
          cd /
          pwd
          whoami
